blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete, HomeIndex

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
    path('', cache_page(60)(HomeIndex), name='home_index'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin', admin.site.urls),
    path('main/', include('main.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    description = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    creation_date = models.DateTimeField(auto_now_add=True,verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title}, {self.description}'

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "статьи"

blog/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Blog
from blog.services import get_articles_cache
from main.models import Mailing


class BlogCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    """Контроллер блога для создания новой статьи"""
    model = Blog
    fields = ('title', 'description', 'preview', 'is_published')
    success_url = reverse_lazy('blog:list')

    def test_func(self):
        user = self.request.user
        if user.groups.filter(name='content_manager').exists() or user.is_superuser:
            return True
        return False

    def form_valid(self, form):
        """Формируем slug-name для заголовка"""
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def handle_no_permission(self):
        return redirect(reverse_lazy('blog:list'))


class BlogListView(ListView):
    """Контроллер блога для просмотра списка статей"""
    model = Blog

    def get_queryset(self, *args, **kwargs):
        """Выводим в общий список только опубликованные записи"""

        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Создаем счетчик просмотров"""

        self.object = super().get_object(queryset)
        self.object.views_count += 1
        print(self.object.views_count)
        self.object.save()

        return self.object


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Контроллер блога для редактирования статьи"""

    model = Blog
    fields = ('title', 'description', 'preview', 'is_published')

    def get_success_url(self):
        """
        Переопределение url-адреса для перенаправления
        после успешного редактирования
        """
        return reverse('blog:view', args=[self.object.pk])

    def test_func(self):
        user = self.request.user
        if user.groups.filter(name='content_manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('blog:list'))


class BlogDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Контроллер блога для удаления статьи"""

    model = Blog
    success_url = reverse_lazy('blog:list')

    def test_func(self):
        user = self.request.user
        if user.groups.filter(name='content_manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('blog:list'))


def HomeIndex(request):
    mailing_count = Mailing.objects.all().count()
    active_count = Mailing.objects.filter(mailing_status=Mailing.STATUS_STARTED).count()
    article_all = get_articles_cache()
    count_article = len(article_all)
    min_article = min(3, count_article)
    article = sample(list(article_all), min_article)
    context = {
        'mailing_count': mailing_count,
        'active_count': active_count,
        'article': article
    }
    return render(request, 'blog/home_index.html', context)

blog/templates/blog/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
{% include 'blog/includes/inc_blog_delete.html' %}
<div class="row">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
</div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить статью {{object.title}}?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
{% include 'blog/includes/inc_blog_detail.html' %}
{% load media_filters %}
<div class="row mx-2">
    <div class="col-md-4 mb-3">
        <img src="{{ blog.preview|mediapath }}" class="img-fluid" alt="{{ blog.title }}">>
    </div>
    <div class="col-md-8 mb-3">
        <p>{{ blog.description }}</p>
    </div>
</div><br><br>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/base.html' %}
{% block content %}
<br>
<h1 align="center">Добавление новой статьи</h1><br><br>
<div class="row"><br>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'main/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore - блог</h1>
</div>
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить статью</a>
</div>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    {{ object.title }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'blog:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">View</a>
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

{% endblock %}

blog/templates/blog/home_index.html
{% extends 'main/base.html' %}
{% load media_filters %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Количество зарегистрированных рассылок: {{ mailing_count }}</h2>
    <h2 class="mb-4">Количество активных рассылок: {{ active_count }}</h2>
    <h2 class="mb-4">Наш блог:</h2>

    <div class="row">
        {% for blog in article %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <img src="{{ blog.preview|mediapath }}" class="card-img-top" alt="{{ article.title }}">
                <div class="card-body">
                    <h4 class="card-title">{{ blog.title }}</h4>
                    <p class="card-text">{{ blog.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Количество просмотров: {{ blog.views_count }}</li>
                    <li class="list-group-item">Дата публикации: {{ blog.creation_date }}</li>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}