blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDelete, HomeIndex

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog/', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDelete.as_view(), name='delete'),
    path('', cache_page(60)(HomeIndex), name='home_index'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin', admin.site.urls),
    path('main/', include('main.urls')),
    path('users/', include('users.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import (MailingListView, MailingCreateView, MailingUpdateView, MailingDetailView, MailingDeleteView,
                        ClientListView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView,
                        mailing_logs)

app_name = MainConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('mailing/<int:mailing_id>/logs', mailing_logs, name='mailing_logs'),
    path('client/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/detail/', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
]

main/models.py
from django.db import models

from config import settings

NULLABLE = {
    'null': True,
    'blank': True
}


class Client(models.Model):
    email = models.EmailField(verbose_name='почта')
    first_name = models.CharField(max_length=100, **NULLABLE, verbose_name='имя')
    last_name = models.CharField(max_length=100, **NULLABLE, verbose_name='фамилия')
    surname = models.CharField(max_length=100, **NULLABLE, verbose_name='отчество')
    comment = models.TextField(**NULLABLE, verbose_name='комментарий')
    client_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        return f'{self.email} ({self.first_name} {self.last_name})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUSES = (
        (STATUS_STARTED, 'Запущена'),
        (STATUS_CREATED, 'Создана'),
        (STATUS_DONE, 'Завершена'),
    )

    send_time = models.TimeField(verbose_name='время рассылки')
    send_frequency = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность')
    mailing_status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_CREATED, verbose_name='статус')
    mailing_clients = models.ManyToManyField(Client, **NULLABLE, verbose_name='подписчики')
    subject = models.CharField(max_length=200, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    mailing_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        return f"Рассылка {self.subject} в {self.send_time} ({self.send_frequency})"

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            ('set_mailing_status', 'Can change the status of mailing'),
        ]


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    log_status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус попытки')
    log_client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='подписчик')
    log_mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    response = models.TextField(**NULLABLE, verbose_name='ответ сервера')

    def __str__(self):
        return f"{self.log_client} - {self.log_mailing} ({self.log_status}) в {self.created_time}"

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from main.form import MailingForm, ClientForm
from main.models import Mailing, Client, MailingLog


class MailingListView(ListView):
    model = Mailing
    extra_context = {
        'title': 'Рассылки'
    }

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='manager').exists() or user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                mailing_owner=user.pk
            )
        return queryset


class MailingCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    extra_context = {
        'title': 'Добавление рассылки'
    }

    def test_func(self):
        user = self.request.user
        if not user.groups.filter(name='manager').exists() and not user.groups.filter(name='content_manager').exists():
            return True
        return False

    def get_success_url(self):
        return reverse('main:mailing_detail', args=[self.object.pk])

    def form_valid(self, form):
        user = self.request.user
        self.object = form.save()
        self.object.mailing_owner = user
        self.object.save()
        return redirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))


class MailingUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    extra_context = {
        'title': 'Изменение рассылки'
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()

        if mailing.mailing_owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))

    def get_success_url(self):
        return reverse('main:mailing_detail', args=[self.object.pk])


class MailingDetailView(DetailView, UserPassesTestMixin):
    model = Mailing
    extra_context = {
        'title': 'Информация о рассылке'
    }

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()

        if mailing.mailing_owner == user or user.groups.filter(name='manager').exists() or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))


class MailingDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('main:mailing_list')
    extra_context = {
        'title': 'Удаление рассылки'
    }

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()

        if mailing.mailing_owner == user or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))


@login_required
def mailing_logs(request, mailing_id):
    mailing = get_object_or_404(Mailing, pk=mailing_id)
    logs = MailingLog.objects.filter(log_mailing=mailing).order_by('-created_time')

    if (mailing.mailing_owner == request.user or request.user.is_superuser
            or request.user.groups.filter(name='manager').exists()):
        context = {
            'mailing': mailing,
            'logs': logs,
        }
        return render(request, 'main/mailing_logs.html', context)
    else:
        return redirect("mail:mailing_list")


class ClientListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Client
    extra_context = {
        'title': 'Мои клиенты'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser:
            queryset = super().get_queryset()
        else:
            queryset = super().get_queryset().filter(
                client_owner=user.pk
            )
        return queryset

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))


class ClientCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Добавление клиента'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))

    def get_success_url(self):
        return reverse('main:client_detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.client_owner = self.request.user
        self.object.save()
        return redirect(self.get_success_url())


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    extra_context = {
        'title': 'Изменение клиента'
    }

    def test_func(self):
        user = self.request.user
        mailing = self.get_object()

        if mailing.client_owner == user or user.is_staff:
            return True
        return False

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.client_owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:client_list'))

    def get_success_url(self):
        return reverse('main:client_detail', args=[self.object.pk])


class ClientDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Client
    extra_context = {
        'title': 'Информация о клиенте'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('main:client_list')
    extra_context = {
        'title': 'Удаление клиента'
    }

    def test_func(self):
        user = self.request.user
        if not user.is_staff or user.is_superuser:
            return True
        return False

    def handle_no_permission(self):
        return redirect(reverse_lazy('main:mailing_list'))

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Менеджер рассылок</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

 <header>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Меню</h5>
    <nav class="ms-5">
        {% if user.is_staff %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:users_list' %}">Пользователи</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'main:mailing_list' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'main:client_list' %}">Клиенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:detail' user.pk %}">Профиль</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>
</header>

<main role="main">



    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-sm-8 col-md-7 py-4 mx-auto text-center">
                <h4 class="text-muted">{{ title }}</h4>
            </div>

            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'blog:home_index' %}">Главная</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                <p> Действительно хотите удалить клиента {{ object.email }}</p>
                <button type="submit" class="btn-outline-danger">
                    Удалить
                </button>
                <a class="btn-outline-warning" href="{% url 'main:client_detail' object.pk %}">Отмена</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/client_detail.html
{% extends 'main/base.html' %}

{% block content %}

<table class="table table-striped">
    <tbody>
    <tr>
        <th scope="row">Электронная почта</th>
        <td>{{ object.email }}</td>
    </tr>
    <tr>
        <th scope="row">Фамилия</th>
        <td>{{ object.last_name }}</td>
    </tr>
    <tr>
        <th scope="row">Имя</th>
        <td>{{ object.first_name }}</td>
    </tr>
    <tr>
        <th scope="row">Отчество</th>
        <td>{{ object.surname }}</td>
    </tr>
    <tr>
        <th scope="row">Комментарий</th>
        <td>{{ object.comment }}</td>
    </tr>
     <tr>
        <th scope="row">Владелец</th>
        <td>{{ object.client_owner }}</td>
    </tr>
    </tbody>
</table>

<div class="text-center">
    <a href="{% url 'main:client_update' object.pk %}" class="btn btn-primary">Изменить</a>
    <a href="{% url 'main:client_delete' object.pk %}" class="btn btn-danger">Удалить</a>
</div>

{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>

{% endblock %}

main/templates/main/client_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <a href="{% url 'main:client_create' %}" class="btn btn-success mb-3">Добавить клиента</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h5 class="card-title">{{ object.email }}</h5>
                <p class="card-text">Фамилия: {{ object.last_name }}</p>
                <p class="card-text">Имя: {{ object.first_name }}</p>
                <p class="card-text">Отчество: {{ object.surname }}</p>
                <p class="card-text">Владелец: {{ object.client_owner }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <a href="{% url 'main:client_detail' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Подробнее</a>
                    <small class="text-muted">{{ object.comment }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/mailing_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
    <form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                <p> Действительно хотите удалить рассылку {{ object.subject }}</p>
                <button type="submit" class="btn-outline-danger">
                    Удалить
                </button>
                <a class="btn-outline-warning" href="{% url 'main:mailing_detail' object.pk %}">Отмена</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/mailing_detail.html
{% extends 'main/base.html' %}

{% block content %}

<table class="table table-striped">
    <thead>
    <tr>
        <th>Тема рассылки</th>
        <th>Сообщение</th>
        <th>Время рассылки</th>
        <th>Периодичность</th>
        <th>Статус</th>
        <th>Подписчики</th>
        <th>Владелец</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>{{ object.subject }}</td>
        <td>{{ object.body }}</td>
        <td>{{ object.send_time }}</td>
        <td>{{ object.send_frequency }}</td>
        <td>{{ object.mailing_status }}</td>
        <td>
            <ul>
                {% for client in mailing.mailing_clients.all %}
                <li>{{ client.email }}</li>
                {% endfor %}
            </ul>
        </td>
        <td>{{ object.mailing_owner }}</td>
    </tr>
    </tbody>
</table>

<div class="text-center">
    <a href="{% url 'main:mailing_logs' object.pk %}" class="btn btn-success">Смотреть отчет</a>
    <a href="{% url 'main:mailing_update' object.pk %}" class="btn btn-primary">Изменить</a>
    <a href="{% url 'main:mailing_delete' object.pk %}" class="btn btn-danger">Удалить</a>
</div>

{% endblock %}

main/templates/main/mailing_form.html
{% extends 'main/base.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>

{% endblock %}

main/templates/main/mailing_list.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <a href="{% url 'main:mailing_create' %}" class="btn btn-success mb-3">Создать рассылку</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h5 class="card-title">{{ object.subject }}</h5>
                <p class="card-text">{{ object.send_frequency }}</p>
                <p class="card-text">{{ object.send_time }}</p>
                <p class="card-text">Владелец {{ object.mailing_owner }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <a href="{% url 'main:mailing_detail' object.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Подробнее</a>
                    <small class="text-muted">{{ object.mailing_status }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/mailing_logs.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Логи рассылки "{{ mailing.subject }}"</h1>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Дата и время</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Подписчик</th>
                    <th scope="col">Ответ сервера</th>
                </tr>
            </thead>
            <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ log.created_time }}</td>
                    <td>
                        {% if log.log_status == 'ok' %}
                        <span class="badge badge-success">Успешно</span>
                        {% else %}
                        <span class="badge badge-danger">Ошибка</span>
                        {% endif %}
                    </td>
                    <td>{{ log.log_client }}</td>
                    <td>{{ log.response }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">Нет доступных логов для этой рассылки.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <a href="{% url 'main:mailing_detail' mailing.pk %}" class="btn btn-secondary">Назад</a>
</div>
{% endblock %}